server {
    listen 80;
    server_name localhost;

    # Localização onde os arquivos estáticos compilados do React foram salvos
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Garante que o roteamento de página única (SPA) funcione sem dar erro 404
        try_files $uri $uri/ /index.html;
    }

    # Proxy Reverso: Encaminha as requisições do backend para o Django
    location /api/ {
        proxy_pass http://${BACKEND_UPSTREAM};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /controles/ {
        proxy_pass http://${BACKEND_UPSTREAM};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /media/ {
        proxy_pass http://${BACKEND_UPSTREAM};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Tratamento padrão para erros de servidor
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
